package interactive.deadsignal.dsi.manager;

import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.os.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.security.MessageDigest;
import java.util.concurrent.*;
import javax.net.ssl.HttpsURLConnection;

/** Original opt-in, same-signer update transport and Android approval bridge. */
public final class ManagerUpdater {
 static final String STORE="dsi.manager.update.v1", PACKAGE="interactive.deadsignal.dsi.manager";
 static final long MAX_APK=128L*1024*1024;
 public interface Listener {void onState(UpdateState state);}
 public static final class UpdateState {
  public final String phase,message,versionName; public final long versionCode; public final boolean updateAvailable,prepared,awaitingApproval; public final int sessionId;
  UpdateState(String phase,String message,String name,long code,boolean available,boolean prepared,boolean approval,int session){this.phase=phase;this.message=message;versionName=name;versionCode=code;updateAvailable=available;this.prepared=prepared;awaitingApproval=approval;sessionId=session;}
 }
 final Context context; final SharedPreferences journal; final ExecutorService worker=Executors.newSingleThreadExecutor(); final Handler main=new Handler(Looper.getMainLooper()); volatile Listener listener; volatile boolean cancelled; final java.util.concurrent.atomic.AtomicBoolean installationQueued=new java.util.concurrent.atomic.AtomicBoolean();
 public ManagerUpdater(Context context){this(context,null);}
 public ManagerUpdater(Context context,Listener listener){this.context=context.getApplicationContext();this.listener=listener;journal=this.context.getSharedPreferences(STORE,0);recover(true);if(journal.contains("approval"))journal.edit().putBoolean("approvalPresented",false).commit();}
 static long version(PackageInfo info){return Build.VERSION.SDK_INT>=28?info.getLongVersionCode():info.versionCode;}
 int flags(){return Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES;}
 static String hex(byte[] bytes){StringBuilder out=new StringBuilder();for(byte value:bytes)out.append(String.format(java.util.Locale.ROOT,"%02x",value&255));return out.toString();}
 String certificate(PackageInfo info)throws Exception{Signature[] signatures;if(Build.VERSION.SDK_INT>=28){if(info.signingInfo==null||info.signingInfo.hasMultipleSigners())throw new IOException("Unsupported update signer layout");signatures=info.signingInfo.getApkContentsSigners();}else signatures=info.signatures;if(signatures==null||signatures.length!=1)throw new IOException("Expected one update signer");return hex(MessageDigest.getInstance("SHA-256").digest(signatures[0].toByteArray()));}
 PackageInfo current()throws Exception{return context.getPackageManager().getPackageInfo(PACKAGE,flags());}
 JSONObject feed(){try{return new JSONObject(journal.getString("feed","{}"));}catch(JSONException error){return new JSONObject();}}
 void transition(String phase,String message){journal.edit().putString("phase",phase).putString("message",message).commit();android.util.Log.i("DSI_MANAGER_UPDATE","phase="+phase+"; "+message);Listener active=listener;if(active!=null)main.post(()->{if(listener!=null)listener.onState(state());});}
 public UpdateState state(){JSONObject data=feed();String phase=journal.getString("phase","IDLE");boolean available=false;try{available=data.optLong("versionCode",0)>version(current())&&!"ERROR".equals(phase)&&!"CANCELLED".equals(phase);}catch(Exception ignored){}int session=journal.getInt("sessionId",-1);return new UpdateState(phase,journal.getString("message","Check DSI releases when you are ready."),data.optString("versionName",""),data.optLong("versionCode",0),available,journal.getBoolean("prepared",false),session>=0&&journal.contains("approval")&&!journal.getBoolean("approvalPresented",false),session);}
 File file(String suffix)throws IOException{File folder=new File(context.getFilesDir(),"verified-update").getCanonicalFile();if(!folder.getParentFile().equals(context.getFilesDir().getCanonicalFile()))throw new IOException("Invalid update staging");if(!folder.exists()&&!folder.mkdir())throw new IOException("Private update staging unavailable");return new File(folder,"manager.apk"+suffix);}
 void cleanup(){try{for(String suffix:new String[]{"",".part"}){File item=file(suffix);if(item.exists()&&!item.delete())android.util.Log.w("DSI_MANAGER_UPDATE","Private staging removal failed");}}catch(Exception ignored){}journal.edit().putBoolean("prepared",false).commit();}
 static boolean assetUrl(URL url){
  if(!"https".equals(url.getProtocol())||url.getUserInfo()!=null||url.getRef()!=null||url.getQuery()!=null||(url.getPort()!=-1&&url.getPort()!=443&&!ManagerUpdateConfig.QA_BUILD))return false;
  if(ManagerUpdateConfig.QA_BUILD)return url.toString().startsWith(ManagerUpdateConfig.QA_ASSET_PREFIX)&&url.getHost().equals("localhost")&&url.getPort()==8443;
  return !url.getPath().contains("/../")&&!url.getPath().contains("/./")&&url.getHost().equals("github.com")&&url.getPath().matches("/raiinman/DSI-CHAT/releases/download/[A-Za-z0-9._-]+/[A-Za-z0-9._-]+\\.apk");
 }
 static boolean redirectedAsset(URL url){if(assetUrl(url))return true;if(ManagerUpdateConfig.QA_BUILD)return false;return "https".equals(url.getProtocol())&&url.getUserInfo()==null&&url.getRef()==null&&(url.getPort()==-1||url.getPort()==443)&&(url.getHost().equals("release-assets.githubusercontent.com")||url.getHost().equals("objects.githubusercontent.com"));}
 HttpsURLConnection connect(URL start,boolean asset)throws Exception{
  URL url=start;for(int redirects=0;redirects<=5;redirects++){
   if(cancelled)throw new InterruptedException("Update cancelled");if(asset?!redirectedAsset(url):!url.toString().equals(ManagerUpdateConfig.FEED_URL))throw new IOException("Update URL is outside the DSI release policy");
   HttpsURLConnection connection=(HttpsURLConnection)url.openConnection();connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(15000);connection.setReadTimeout(15000);connection.setRequestProperty("Accept-Encoding","identity");connection.setRequestProperty("User-Agent","DSI-Manager/0.3");int status=connection.getResponseCode();
   if(status==200)return connection;
   if(asset&&(status==301||status==302||status==303||status==307||status==308)){String location=connection.getHeaderField("Location");connection.disconnect();if(location==null)throw new IOException("Release redirect is missing its destination");url=new URL(url,location);continue;}
   connection.disconnect();throw new IOException("DSI release server returned HTTP "+status);
  }throw new IOException("Too many release redirects");
 }
 void validate(JSONObject data,boolean requireNew)throws Exception{
  PackageInfo installed=current();long code=data.getLong("versionCode"),size=data.getLong("bytes");
  if(data.getInt("schemaVersion")!=1||!PACKAGE.equals(data.getString("package"))||code<=0||code<version(installed)||(requireNew&&code<=version(installed)))throw new IOException("Update package/version is invalid or would downgrade this Manager");
  if(data.getInt("minSdk")<26||data.getInt("minSdk")>Build.VERSION.SDK_INT||size<=0||size>MAX_APK||!data.getString("sha256").matches("[a-f0-9]{64}")||!data.getString("certificateSha256").equals(certificate(installed))||!assetUrl(new URL(data.getString("url")))||data.getString("versionName").length()>100)throw new IOException("Update metadata, platform, URL or signing certificate is unsupported");
 }
 public synchronized void check()throws Exception{
  if(installationQueued.get()||state().sessionId>=0)throw new IOException("Finish or cancel the current update first");cancelled=false;cleanup();transition("CHECKING","Checking the fixed DSI release feed.");HttpsURLConnection connection=null;
  try{connection=connect(new URL(ManagerUpdateConfig.FEED_URL),false);ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(InputStream input=connection.getInputStream()){byte[] buffer=new byte[4096];int read;while((read=input.read(buffer))!=-1){if(cancelled)throw new InterruptedException("Update cancelled");if(bytes.size()+read>65536)throw new IOException("Update feed exceeds its size limit");bytes.write(buffer,0,read);}}JSONObject data=new JSONObject(bytes.toString("UTF-8"));validate(data,false);if(cancelled)throw new InterruptedException("Update cancelled");journal.edit().putString("feed",data.toString()).commit();transition(data.getLong("versionCode")==version(current())?"UP_TO_DATE":"AVAILABLE",data.getLong("versionCode")==version(current())?"You have the current verified DSI release.":"A same-signer DSI update is available. Download it when ready.");}
  catch(Exception error){transition(cancelled?"CANCELLED":"ERROR",cancelled?"Update check cancelled.":error.getMessage());throw error;}finally{if(connection!=null)connection.disconnect();}
 }
 void verify(File apk,JSONObject data)throws Exception{
  validate(data,true);if(apk.length()!=data.getLong("bytes"))throw new IOException("Update size does not match the release feed");MessageDigest digest=MessageDigest.getInstance("SHA-256");try(InputStream input=new FileInputStream(apk)){byte[] buffer=new byte[16384];int read;while((read=input.read(buffer))!=-1){if(cancelled)throw new InterruptedException("Update cancelled");digest.update(buffer,0,read);}}if(!hex(digest.digest()).equals(data.getString("sha256")))throw new IOException("Update SHA-256 integrity check failed");
  PackageInfo info=context.getPackageManager().getPackageArchiveInfo(apk.getAbsolutePath(),flags());if(info==null||info.applicationInfo==null||!PACKAGE.equals(info.packageName)||version(info)!=data.getLong("versionCode")||info.applicationInfo.minSdkVersion!=data.getInt("minSdk")||!certificate(info).equals(certificate(current()))||(info.applicationInfo.flags&ApplicationInfo.FLAG_TEST_ONLY)!=0)throw new IOException("Update APK package/version/SDK/signing certificate verification failed");
 }
 public synchronized void download()throws Exception{
  if(installationQueued.get()||state().sessionId>=0)throw new IOException("Finish or cancel the current update first");cancelled=false;JSONObject data=feed();HttpsURLConnection connection=null;
  try{validate(data,true);cleanup();transition("DOWNLOADING","Downloading the selected DSI release and checking its integrity.");connection=connect(new URL(data.getString("url")),true);long expected=data.getLong("bytes"),count=0;File part=file(".part");try(InputStream input=connection.getInputStream();OutputStream output=new FileOutputStream(part)){byte[] buffer=new byte[16384];int read;while((read=input.read(buffer))!=-1){if(cancelled)throw new InterruptedException("Update cancelled");count+=read;if(count>expected)throw new IOException("Update download exceeded declared size");output.write(buffer,0,read);}}verify(part,data);if(cancelled)throw new InterruptedException("Update cancelled");File target=file("");if(target.exists()&&!target.delete())throw new IOException("Private update staging could not be cleared");if(!part.renameTo(target))throw new IOException("Verified update could not be staged");journal.edit().putBoolean("prepared",true).commit();transition("READY","Verified DSI update is ready for Android's installation approval.");}
  catch(Exception error){cleanup();transition(cancelled?"CANCELLED":"ERROR",cancelled?"Update download cancelled.":error.getMessage());throw error;}finally{if(connection!=null)connection.disconnect();}
 }
 public void requestUpdate(Activity activity)throws Exception{
  if(state().awaitingApproval){continueApproval(activity);return;}if(state().sessionId>=0)return;if(!state().prepared)throw new IOException("Download and verify the update first");if(!context.getPackageManager().canRequestPackageInstalls())throw new IOException("Allow installation from DSI Manager in Android settings first");
  if(!installationQueued.compareAndSet(false,true))return;
  cancelled=false;transition("AWAITING_INSTALL","Preparing Android's explicit update approval.");worker.execute(()->{int id=-1;try{JSONObject data=feed();File apk=file("");verify(apk,data);PackageInstaller installer=context.getPackageManager().getPackageInstaller();PackageInstaller.SessionParams params=new PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL);params.setAppPackageName(PACKAGE);params.setSize(apk.length());if(Build.VERSION.SDK_INT>=31)params.setRequireUserAction(PackageInstaller.SessionParams.USER_ACTION_REQUIRED);id=installer.createSession(params);journal.edit().putInt("sessionId",id).remove("approval").putBoolean("approvalPresented",false).commit();try(PackageInstaller.Session session=installer.openSession(id)){try(InputStream input=new FileInputStream(apk);OutputStream output=session.openWrite("base.apk",0,apk.length())){byte[] buffer=new byte[16384];int read;while((read=input.read(buffer))!=-1){if(cancelled)throw new InterruptedException("Update cancelled");output.write(buffer,0,read);}session.fsync(output);}Intent callback=new Intent(context,UpdateReceiver.class).setAction("interactive.deadsignal.dsi.manager.UPDATE_RESULT").putExtra("ownedSession",id);PendingIntent sender=PendingIntent.getBroadcast(context,id,callback,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0));if(cancelled)throw new InterruptedException("Update cancelled");session.commit(sender.getIntentSender());}}
  catch(Exception error){abandon(id);cleanup();transition(cancelled?"CANCELLED":"ERROR",cancelled?"Update cancelled.":error.getMessage());}finally{installationQueued.set(false);}});
 }
 public void continueApproval(Activity activity)throws Exception{String stored=journal.getString("approval",null);if(stored==null)return;activity.startActivity(Intent.parseUri(stored,Intent.URI_INTENT_SCHEME));journal.edit().putBoolean("approvalPresented",true).commit();transition("AWAITING_INSTALL","Review Android's update prompt. Existing Manager settings are preserved.");}
 void abandon(int id){if(id>=0)try{context.getPackageManager().getPackageInstaller().abandonSession(id);}catch(RuntimeException ignored){}journal.edit().putInt("sessionId",-1).remove("approval").commit();}
 public void cancel(){cancelled=true;abandon(journal.getInt("sessionId",-1));cleanup();transition("CANCELLED","Update cancelled. Installed apps and settings are preserved.");}
 void recover(boolean interrupted){int id=journal.getInt("sessionId",-1);String priorPhase=journal.getString("phase","");boolean ownedInstall=id>=0||"AWAITING_INSTALL".equals(priorPhase)||"INSTALLED".equals(priorPhase);try{if(ownedInstall&&feed().optLong("versionCode",0)>0&&version(current())>=feed().optLong("versionCode",0)){journal.edit().putInt("sessionId",-1).remove("approval").commit();cleanup();transition("INSTALLED","You have the selected DSI release. Your Manager settings were retained.");return;}}catch(Exception ignored){}if(id>=0&&context.getPackageManager().getPackageInstaller().getSessionInfo(id)==null){journal.edit().putInt("sessionId",-1).remove("approval").commit();cleanup();transition("ERROR","The previous update session ended. Check for updates again.");}else if(interrupted&&id<0&&("DOWNLOADING".equals(journal.getString("phase",""))||"CHECKING".equals(journal.getString("phase","")))){cleanup();transition("ERROR","The previous update operation was interrupted. Check again.");}}
 public void refresh(){recover(false);} public void close(){listener=null;worker.shutdown();}
 static void result(Context context,Intent intent){SharedPreferences journal=context.getSharedPreferences(STORE,0);int saved=journal.getInt("sessionId",-1),returned=intent.getIntExtra(PackageInstaller.EXTRA_SESSION_ID,intent.getIntExtra("ownedSession",-2));if(saved<0||saved!=returned)return;int status=intent.getIntExtra(PackageInstaller.EXTRA_STATUS,PackageInstaller.STATUS_FAILURE);if(status==PackageInstaller.STATUS_PENDING_USER_ACTION){Intent approval=intent.getParcelableExtra(Intent.EXTRA_INTENT);if(approval!=null)journal.edit().putString("approval",approval.toUri(Intent.URI_INTENT_SCHEME)).putBoolean("approvalPresented",false).putString("phase","AWAITING_INSTALL").putString("message","Continue to Android's update approval.").commit();return;}journal.edit().putInt("sessionId",-1).remove("approval").putString("phase",status==PackageInstaller.STATUS_SUCCESS?"INSTALLED":status==PackageInstaller.STATUS_FAILURE_ABORTED?"CANCELLED":"ERROR").putString("message",status==PackageInstaller.STATUS_SUCCESS?"DSI Manager was updated.":"Android did not complete the update.").commit();try{ManagerUpdater owner=new ManagerUpdater(context);owner.cleanup();owner.close();}catch(RuntimeException ignored){} }
}
