import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {WorkspaceService,createTemplate} from './service.mjs';
async function fixture(t){const base=await fs.mkdtemp(path.join(os.tmpdir(),'dsi-redteam-'));t.after(()=>fs.rm(base,{recursive:true,force:true}));const root=path.join(base,'selected'),outside=path.join(base,'outside');await fs.mkdir(outside);await createTemplate(root);const service=new WorkspaceService();await service.open(root);await fs.writeFile(path.join(outside,'sentinel.ts'),'OUTSIDE_SENTINEL');return {base,root,outside,service};}
test('hostile read/save paths cannot access or mutate an outside sentinel',async t=>{const {root,outside,service}=await fixture(t);const paths=['../outside/sentinel.ts','..\\outside\\sentinel.ts',path.join(outside,'sentinel.ts'),'\\\\localhost\\nonexistent\\sentinel.ts',null,{},''];for(const candidate of paths){await assert.rejects(service.read(candidate));await assert.rejects(service.save({path:candidate,text:'ATTACK',revision:null}));}assert.equal(await fs.readFile(path.join(outside,'sentinel.ts'),'utf8'),'OUTSIDE_SENTINEL');assert.match((await service.read('plugin.ts')).text,/Original DSI sample/);});
test('junction output cannot redirect build/package writes into outside files',async t=>{const {root,outside,service}=await fixture(t);await fs.symlink(outside,path.join(root,'.dsi-build'),process.platform==='win32'?'junction':'dir');await assert.rejects(service.build(),/symlink/i);await assert.rejects(service.package(),/symlink/i);assert.equal(await fs.readFile(path.join(outside,'sentinel.ts'),'utf8'),'OUTSIDE_SENTINEL');assert.equal(await fs.access(path.join(outside,'plugin.mjs')).then(()=>true,()=>false),false);});
test('symlink output leaf cannot redirect writes when host permits file symlinks',async t=>{const {root,outside,service}=await fixture(t);await service.build();const output=path.join(root,'.dsi-build/plugin.mjs');await fs.unlink(output);try{await fs.symlink(path.join(outside,'sentinel.ts'),output,process.platform==='win32'?'file':undefined);}catch(error){if(['EPERM','ENOTSUP','EOPNOTSUPP'].includes(error.code)){t.skip('Host does not permit file symlinks: '+error.code);return;}throw error;}await assert.rejects(service.build(),/symlink/i);assert.equal(await fs.readFile(path.join(outside,'sentinel.ts'),'utf8'),'OUTSIDE_SENTINEL');});
test('hidden symlink declaration inputs cannot leak sentinel diagnostics or become bundled imports',async t=>{const {root,outside,service}=await fixture(t);await fs.writeFile(path.join(outside,'private.d.ts'),'export declare const value: "SECRET_TYPE_SENTINEL";');await fs.symlink(outside,path.join(root,'private'),process.platform==='win32'?'junction':'dir');const original=await service.read('plugin.ts');await service.save({...original,text:original.text+'\nimport {value} from "./private/private.d.ts"; const leaked: number=value;'});const result=await service.diagnostics();assert.equal(result.ok,false);assert.ok(result.errors.every(item=>!item.message.includes('SECRET_TYPE_SENTINEL')));assert.ok(result.errors.some(item=>/Cannot find module/.test(item.message)));assert.equal((await service.build()).ok,false);});
test('absolute dynamic imports and remote imports are not bundled by the selected-workspace resolver',async t=>{const {service}=await fixture(t);const original=await service.read('plugin.ts');for(const target of ['node:fs','https://example.invalid/never-requested.js','file:///C:/outside.ts']){await service.save({...await service.read('plugin.ts'),text:original.text+'\nimport('+JSON.stringify(target)+');'});const result=await service.diagnostics();if(result.ok)await assert.rejects(service.build(),/relative imports/);else assert.ok(result.errors.some(item=>/Cannot find module/.test(item.message)));}});
test('save conflict cannot be bypassed with omitted or forged revisions',async t=>{const {root,service}=await fixture(t);const original=await service.read('plugin.ts');for(const revision of [undefined,null,'0'.repeat(64),original.revision+'x'])await assert.rejects(service.save({path:'plugin.ts',text:'ATTACK',revision}),/External change/);assert.equal(await fs.readFile(path.join(root,'plugin.ts'),'utf8'),original.text);});
test('multiply-linked source cannot read/save an outside sentinel',async t=>{const {root,outside,service}=await fixture(t);try{await fs.link(path.join(outside,'sentinel.ts'),path.join(root,'linked.ts'));}catch(error){if(['EPERM','ENOTSUP','EOPNOTSUPP'].includes(error.code)){t.skip('Host filesystem cannot create hardlinks: '+error.code);return;}throw error;}await assert.rejects(service.read('linked.ts'),/multiply-linked/);await assert.rejects(service.save({path:'linked.ts',text:'ATTACK',revision:null}),/multiply-linked/);assert.equal(await fs.readFile(path.join(outside,'sentinel.ts'),'utf8'),'OUTSIDE_SENTINEL');});
test('multiply-linked output cannot overwrite an outside sentinel during build',async t=>{const {root,outside,service}=await fixture(t);await service.build();await fs.unlink(path.join(root,'.dsi-build/plugin.mjs'));try{await fs.link(path.join(outside,'sentinel.ts'),path.join(root,'.dsi-build/plugin.mjs'));}catch(error){if(['EPERM','ENOTSUP','EOPNOTSUPP'].includes(error.code)){t.skip('Host filesystem cannot create hardlinks: '+error.code);return;}throw error;}await assert.rejects(service.build(),/multiply-linked build output/);assert.equal(await fs.readFile(path.join(outside,'sentinel.ts'),'utf8'),'OUTSIDE_SENTINEL');});
test('Windows named streams and drive-relative paths cannot create hidden editor content',async t=>{if(process.platform!=='win32'){t.skip('NTFS alternate data streams are Windows-specific');return;}const {root,service}=await fixture(t);for(const name of ['plugin.ts:invisible.ts','C:relative.ts']){await assert.rejects(service.save({path:name,text:'ATTACK',revision:null}),/streams|drive-relative/);await assert.rejects(service.read(name),/streams|drive-relative/);}assert.equal(await fs.access(path.join(root,'plugin.ts:invisible.ts')).then(()=>true,()=>false),false);});
test('synchronously busy test cancellation finishes and a following test can run',async t=>{const {service}=await fixture(t);const original=await service.read('plugin.test.mjs');await service.save({...original,text:'while(true){}'});const running=service.test();await new Promise(resolve=>setTimeout(resolve,200));const started=Date.now();assert.equal(service.cancel().cancelled,true);const result=await Promise.race([running,new Promise((_,reject)=>setTimeout(()=>reject(Error('Cancel exceeded 2 seconds')),2000))]);assert.equal(result.cancelled,true);assert.equal(result.ok,false);assert.ok(Date.now()-started<2000);await service.save({...await service.read('plugin.test.mjs'),text:'import test from "node:test";test("recovered",()=>{});'});assert.equal((await service.test()).ok,true);});
