import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {WorkspaceService,createTemplate} from './service.mjs';
async function workspace(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'dsi-ide-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await createTemplate(root);const service=new WorkspaceService();await service.open(root);return {root,service};}
test('save rejects external changes while preserving disk and supports corrected reload',async t=>{const {root,service}=await workspace(t);const read=await service.read('plugin.ts');await fs.appendFile(path.join(root,'plugin.ts'),'\n// external');await assert.rejects(service.save({...read,text:'replacement'}),/External change/);assert.match((await service.read('plugin.ts')).text,/external/);const fresh=await service.read('plugin.ts');await service.save({...fresh,text:fresh.text+'\n// saved'});assert.match((await service.read('plugin.ts')).text,/saved/);});
test('workspace rejects absolute, traversal and symlink escapes',async t=>{const {root,service}=await workspace(t);await assert.rejects(service.read('../other.ts'),/escapes/);await assert.rejects(service.read(path.resolve(root,'plugin.ts')),/relative/);const outside=await fs.mkdtemp(path.join(os.tmpdir(),'dsi-outside-'));t.after(()=>fs.rm(outside,{recursive:true,force:true}));await fs.writeFile(path.join(outside,'secret.ts'),'private');await fs.symlink(outside,path.join(root,'escape'),'junction');await assert.rejects(service.read('escape/secret.ts'),/Symlink escapes/);});
test('original template diagnoses, builds, tests and exports checksummed development package',async t=>{const {service}=await workspace(t);assert.equal((await service.diagnostics()).ok,true);assert.equal((await service.build()).ok,true);assert.equal((await service.test()).ok,true);const artifact=JSON.parse((await service.package()).text);assert.equal(artifact.reviewed,false);assert.equal(artifact.format,'dsi-development-plugin');assert.match(artifact.sha256,/^[a-f0-9]{64}$/);assert.match(artifact.source,/dsi-workbench-sample/);});
test('deliberate syntax/manifest errors are reported and correction rebuilds',async t=>{const {service}=await workspace(t);const original=await service.read('plugin.ts');await service.save({...original,text:'export default { broken: ; }'});const diagnostics=await service.diagnostics();assert.equal(diagnostics.ok,false);assert.equal(diagnostics.errors[0].file,'plugin.ts');const broken=await service.read('plugin.ts');await service.save({...broken,text:original.text});assert.equal((await service.build()).ok,true);const manifest=await service.read('manifest.json');await service.save({...manifest,text:'{"id":"invalid"}'});assert.equal((await service.diagnostics()).errors[0].file,'manifest.json');});
test('test process supports cancellation and a subsequent clean run',async t=>{const {service}=await workspace(t);const record=await service.read('plugin.test.mjs');await service.save({...record,text:'setTimeout(()=>{},60000);'});const running=service.test();await new Promise(resolve=>setTimeout(resolve,150));assert.equal(service.cancel().cancelled,true);assert.equal((await running).ok,false);const modified=await service.read('plugin.test.mjs');await service.save({...modified,text:record.text});assert.equal((await service.test()).ok,true);});
test('build refuses escaping output symlink',async t=>{const {root,service}=await workspace(t);const outside=await fs.mkdtemp(path.join(os.tmpdir(),'dsi-output-'));t.after(()=>fs.rm(outside,{recursive:true,force:true}));await fs.symlink(outside,path.join(root,'.dsi-build'),'junction');await assert.rejects(service.build(),/symlink escapes/);});
test('type errors point to the authored file and invalid code cannot package',async t=>{const {service}=await workspace(t);const record=await service.read('plugin.ts');await service.save({...record,text:record.text+'\nconst typed: number = "incorrect";\n'});const diagnostics=await service.diagnostics();assert.equal(diagnostics.ok,false);assert.ok(diagnostics.errors.some(error=>error.file==='plugin.ts'&&error.line>1&&/not assignable/.test(error.message)));assert.equal((await service.package()).ok,false);});
test('bundler rejects imports outside the selected workspace',async t=>{const {root,service}=await workspace(t);const record=await service.read('plugin.ts');await service.save({...record,text:record.text+'\nimport "../escape.js";'});await assert.rejects(service.build(),/escapes selected workspace|Cannot find module/);assert.equal(await fs.access(path.join(root,'.dsi-build/plugin.mjs')).then(()=>true,()=>false),false);});
test('type diagnostics cannot read external imports or escaped symlink modules',async t=>{const {root,service}=await workspace(t);const outside=await fs.mkdtemp(path.join(os.tmpdir(),'dsi-types-outside-'));t.after(()=>fs.rm(outside,{recursive:true,force:true}));await fs.writeFile(path.join(outside,'secret.ts'),'export const privateValue: number = "FILE_CONTENT_SENTINEL";');await fs.symlink(outside,path.join(root,'escape'),'junction');const record=await service.read('plugin.ts');await service.save({...record,text:record.text+'\nimport { privateValue } from "./escape/secret.ts";\nconsole.log(privateValue);'});const diagnostics=await service.diagnostics();assert.equal(diagnostics.ok,false);assert.ok(diagnostics.errors.some(error=>/Cannot find module/.test(error.message)));assert.ok(diagnostics.errors.every(error=>error.file==='plugin.ts'&&!error.message.includes('FILE_CONTENT_SENTINEL')));});
test('a rejected project open preserves the existing selected workspace',async t=>{const {root,service}=await workspace(t);const oversized=await fs.mkdtemp(path.join(os.tmpdir(),'dsi-too-large-'));t.after(()=>fs.rm(oversized,{recursive:true,force:true}));await Promise.all(Array.from({length:501},(_,index)=>fs.writeFile(path.join(oversized,index+'.js'),'// sample')));await assert.rejects(service.open(oversized),/500 editable/);assert.equal(service.root,await fs.realpath(root));assert.match((await service.read('plugin.ts')).text,/Original DSI sample/);});
